import { Language } from "./types";

export const TRANSLATIONS = {
  en: {
    welcome: "Let's set up your business",
    subtitle: "Automate your growth in 10 minutes",
    next: "Next",
    back: "Back",
    finish: "Start Automation",
    loading: "AI is analyzing your business...",
    loadingSub: "Calculating margins, finding customers, and building your roadmap.",
    step1: "Product Details",
    step2: "Business Stage",
    step3: "Resources",
    step4: "Goals",
    step5: "Location",
    
    // Labels
    whatMake: "What do you make?",
    category: "Category",
    capacity: "Daily Production Capacity",
    sellPrice: "Selling Price (₹)",
    costPrice: "Production Cost (₹)",
    experience: "Experience Level",
    revenue: "Monthly Revenue",
    channels: "Where do you sell?",
    customers: "Customer Count",
    budget: "Budget for Growth (₹)",
    team: "Team Size",
    smartphone: "Have Smartphone & Internet?",
    shipping: "Shipping Capability",
    struggle: "Biggest Struggle",
    goal: "3-Month Goal",
    location: "Location (City/District)",
    travel: "Willingness to Travel",
    
    // Dashboard
    activeAutomations: "Active Automations",
    tasksToday: "Tasks Today",
    nextAction: "Next Action",
    roadmap: "Your Automation Roadmap",
    actionItems: "Live Action Items",
    insights: "Smart Insights",
    modules: "Business Modules",
    
    // Status
    running: "Auto-Running",
    approval: "Needs Approval",
    ready: "Ready",
    notStarted: "Not Started",

    // Customer Discovery
    discTitle: "Finding Your Premium Customers",
    discSummary: "Based on your A2 ghee production (15L/day, ₹450 cost, Tiruchirappalli location), we've identified 4 customer segments willing to pay ₹900-1200/litre.",
    segments: "Target Customer Segments",
    intelligence: "Market Intelligence Dashboard",
    actionPlan: "Auto-Generated Action Plan",
    smartTools: "Smart Tools",
    askAi: "Ask AI",
    
    // Marketing
    mktTitle: "Smart Marketing & Lead Engine",
    mktSummary: "You produce 15L A2 ghee per day at ₹450 cost. We’ll help you sell at ₹900–1000/L to city consumers using automated WhatsApp, Instagram, and store outreach.",
    campaignControl: "Campaign Control Center",
    marketingGoal: "Marketing Goal",
    channelMix: "Channel Mix Planner",
    autoSchedule: "Auto-Schedule Engine",
    contentEngine: "WhatsApp & Social Media Engine",
    leadsPerformance: "Lead Pipeline & Performance",
    leadInbox: "Lead Inbox",
    
    // Inventory
    invTitle: "Smart Inventory & Production Control",
    snapshot: "Today & This Week Snapshot",
    prodTracker: "Production Tracker",
    stockBalance: "Stock & Order Balance",
    costAssistant: "Cost & Pricing Assistant",
    
    // Inventory Labels
    todaysProd: "Today's Production",
    availStock: "Available Sale Stock",
    demandCap: "Demand vs Capacity",
    alerts: "Alerts",
    dailyLog: "Daily Production Log",
    planWiz: "Production Planning Wizard",
    bulkStock: "Bulk Ghee Stock",
    packagedUnits: "Packaged Units",
    packagingMat: "Packaging Materials",
    costBreakdown: "Cost Breakdown Per Litre",
    priceSim: "Price Scenario Simulator",

    // Finance
    finTitle: "Smart Money & Profit Dashboard",
    quickHealth: "Quick Health Snapshot",
    moneyIn: "Money In (Sales)",
    moneyOut: "Money Out (Expenses)",
    profitScenarios: "Profitability & Scenarios",
    
    // Finance Labels
    estSales: "Est. Sales This Month",
    estExp: "Est. Expenses This Month",
    projProfit: "Projected Profit",
    salesTracker: "Sales Tracker",
    payModes: "Payment Modes",
    receivables: "Receivables",
    monthlyCost: "Monthly Cost Overview",
    estCostLitre: "Est. Cost Per Litre",
    breakeven: "Breakeven Calculator",
    scenarioSim: "Scenario Simulator",
    cashFlow: "Cash Flow Glimpse",

    // Customer Care
    careTitle: "Customer Care & Repeat Business",
    inbox: "Conversation Inbox",
    smartReplies: "Smart Replies & FAQ Brain",
    feedback: "Feedback & Ratings",
    repeatOrders: "Repeat Order & Loyalty",

    // Care Labels
    unifiedInbox: "Unified Inbox",
    quickAdd: "Quick Add Conversation",
    priorityAlerts: "Priority Alerts",
    faqLibrary: "FAQ Library",
    autoReply: "Auto Reply Suggestion",
    feedbackLog: "Feedback Log",
    satisfaction: "Satisfaction Overview",
    repeatTracker: "Repeat Order Tracker",
    loyalty: "Simple Loyalty Ideas",

    // Logistics
    logTitle: "Smart Logistics & Delivery Planning",
    strategyOverview: "Delivery Strategy Overview",
    cityPlans: "City-Wise Delivery Plans",
    costCalc: "Cost Calculator",
    routeBatch: "Route & Batch Planning",
    
    // Logistics Labels
    keyCities: "Key Cities",
    strategySummary: "Strategy Summary",
    deliveryProfiles: "Delivery Profiles",
    deliveryPromise: "Delivery Promise",
    perOrderCalc: "Per-Order Cost Simulator",
    batchPlan: "Upcoming Batches",
    localRoute: "Local Route Optimization",

    // Compliance
    compTitle: "Compliance, Licences & Registrations (Tamil Nadu)",
    compSubtitle: "Guidance for small producers - Consult a professional for final advice.",
    overview: "Simple Overview",
    keyRegs: "Key Registrations",
    checklists: "Practical Checklists",
    docTracker: "Document & Renewal Reminders",
    
    // Compliance Labels
    whereStand: "Where You Stand",
    whyMatter: "Why Compliance Matters?",
    fssai: "FSSAI (Food Safety)",
    gst: "GST (Tax)",
    shops: "Shops & Est. / Trade License",
    labeling: "Packaging Norms",
    msme: "MSME / Udyam",
    askConsultant: "Ask a Consultant",
    fssaiPrep: "FSSAI Prep List",
    labelCheck: "Label Checklist",
    bigBuyers: "What Big Buyers Ask For",

    // Tools
    distCalc: "Distance Calculator",
    priceEngine: "Price Recommendation Engine",
    listExport: "Contact List Exporter",
    calculate: "Calculate",
    download: "Download Leads (Excel)",

    // Demo
    startDemo: "Start Demo (Ghee Producer)",
    demoMode: "Demo Mode",
    demoGuideTitle: "Demo Guide – Ghee Producer Journey",
    exitDemo: "Exit Demo Mode",
    nextStep: "Next Step",
    demoStep1: "Business Setup",
    demoStep1Desc: "See how the system understands the ghee producer from Tiruchirappalli (20 cows, 15L/day).",
    demoStep2: "Where Customers Are",
    demoStep2Desc: "Identify the best premium customers in Chennai/Coimbatore.",
    demoStep3: "How We Reach Them",
    demoStep3Desc: "Design WhatsApp + Instagram campaigns and B2B outreach automatically.",
    demoStep4: "Can We Supply?",
    demoStep4Desc: "Check production, stock and whether we can meet this new demand.",
    demoStep5: "Financial Viability",
    demoStep5Desc: "See revenue, costs and profit projections for this ghee business.",
    demoStep6: "How to Deliver?",
    demoStep6Desc: "Estimate courier costs and plan shipments from Trichy to cities.",
    demoStep7: "Customer Care",
    demoStep7Desc: "Handle questions, feedback and repeat orders efficiently.",
    goToModule: "Open Module",
    goToSummary: "Go to Summary"
  },
  ta: {
    welcome: "உங்கள் தொழிலை அமைப்போம்",
    subtitle: "10 நிமிடங்களில் உங்கள் வளர்ச்சியை தானியங்குபடுத்துங்கள்",
    next: "அடுத்து (Next)",
    back: "பின்னால் (Back)",
    finish: "தொடங்கவும் (Start)",
    loading: "AI உங்கள் தொழிலை ஆய்வு செய்கிறது...",
    loadingSub: "லாபத்தை கணக்கிடுகிறது, வாடிக்கையாளர்களை தேடுகிறது...",
    step1: "தயாரிப்பு விவரங்கள்",
    step2: "தொழில் நிலை",
    step3: "வளங்கள்",
    step4: "இலக்குகள்",
    step5: "இடம்",

    whatMake: "நீங்கள் என்ன தயாரிக்கிறீர்கள்?",
    category: "வகை (Category)",
    capacity: "தினசரி உற்பத்தி திறன்",
    sellPrice: "விற்பனை விலை (₹)",
    costPrice: "உற்பத்தி செலவு (₹)",
    experience: "அனுபவம்",
    revenue: "மாதாந்திர வருமானம்",
    channels: "எங்கே விற்கிறீர்கள்?",
    customers: "வாடிக்கையாளர் எண்ணிக்கை",
    budget: "வளர்ச்சிக்கான பட்ஜெட் (₹)",
    team: "குழு அளவு",
    smartphone: "ஸ்மார்ட்போன் மற்றும் இணையம் உள்ளதா?",
    shipping: "ஷிப்பிங் வசதி",
    struggle: "மிகப்பெரிய சவால்",
    goal: "3 மாத இலக்கு",
    location: "இடம் (நகரம்/மாவட்டம்)",
    travel: "பயண விருப்பம்",

    activeAutomations: "செயலில் உள்ள தானியக்கங்கள்",
    tasksToday: "இன்றைய பணிகள்",
    nextAction: "அடுத்த நடவடிக்கை",
    roadmap: "உங்கள் வளர்ச்சி திட்டம்",
    actionItems: "நேரடி நடவடிக்கைகள்",
    insights: "நுண்ணறிவு (Insights)",
    modules: "வணிகத் தொகுதிகள்",

    running: "தானாக இயங்குகிறது",
    approval: "ஒப்புதல் தேவை",
    ready: "தயார்",
    notStarted: "தொடங்கப்படவில்லை",

    // Customer Discovery
    discTitle: "உங்கள் தரமான வாடிக்கையாளர்களைக் கண்டறிதல்",
    discSummary: "உங்கள் A2 நெய் உற்பத்தி (15லி/நாள், ₹450 அடக்கம், திருச்சி) அடிப்படையில், ₹900-1200 வரை வாங்கத் தயாராக உள்ள 4 வாடிக்கையாளர் பிரிவுகளைக் கண்டறிந்துள்ளோம்.",
    segments: "இலக்கு வாடிக்கையாளர் பிரிவுகள்",
    intelligence: "சந்தை நிலவரம்",
    actionPlan: "தானியங்கி செயல் திட்டம்",
    smartTools: "ஸ்மார்ட் கருவிகள்",
    askAi: "AI-யிடம் கேளுங்கள்",
    
    // Marketing
    mktTitle: "செயல்முறை சந்தைப்படுத்தல் & வாடிக்கையாளர் உருவாக்கம்",
    mktSummary: "உங்கள் 15L A2 நெய் உற்பத்தியை (அடக்கம் ₹450) நகர வாடிக்கையாளர்களுக்கு ₹900–1000/L விலையில் விற்க WhatsApp, Instagram மற்றும் நேரடி அணுகுமுறை மூலம் உதவுகிறோம்.",
    campaignControl: "பிரச்சார கட்டுப்பாட்டு மையம்",
    marketingGoal: "சந்தைப்படுத்தல் இலக்கு",
    channelMix: "சேனல் திட்டமிடல்",
    autoSchedule: "தானியங்கி அட்டவணை",
    contentEngine: "WhatsApp & சமூக ஊடக இயந்திரம்",
    leadsPerformance: "விற்பனை வாய்ப்புகள் & செயல்திறன்",
    leadInbox: "விற்பனை வாய்ப்புகள் (Leads)",

    // Inventory
    invTitle: "செயல்முறை சரக்கு & உற்பத்தி மேலாண்மை",
    snapshot: "இன்றைய & இந்த வார நிலவரம்",
    prodTracker: "உற்பத்தி கண்காணிப்பு",
    stockBalance: "சரக்கு & ஆர்டர் சமநிலை",
    costAssistant: "செலவு & விலை உதவியாளர்",

    // Inventory Labels
    todaysProd: "இன்றைய உற்பத்தி",
    availStock: "விற்பனைக்கு உள்ள சரக்கு",
    demandCap: "தேவை vs திறன்",
    alerts: "எச்சரிக்கைகள்",
    dailyLog: "தினசரி உற்பத்தி பதிவு",
    planWiz: "உற்பத்தி திட்டமிடல்",
    bulkStock: "மொத்த நெய் இருப்பு",
    packagedUnits: "பேக் செய்யப்பட்ட அலகுகள்",
    packagingMat: "பேக்கிங் பொருட்கள்",
    costBreakdown: "ஒரு லிட்டர் செலவு விவரம்",
    priceSim: "விலை கணிப்பான்",

    // Finance
    finTitle: "செயல்முறை நிதி & லாப கண்காணிப்பு",
    quickHealth: "விரைவு நிதி நிலைமை",
    moneyIn: "பணம் உள்ளே (விற்பனை)",
    moneyOut: "பணம் வெளியே (செலவுகள்)",
    profitScenarios: "லாபம் & காட்சிகள்",
    
    // Finance Labels
    estSales: "இந்த மாத விற்பனை (கணிப்பு)",
    estExp: "இந்த மாத செலவுகள் (கணிப்பு)",
    projProfit: "எதிர்பார்க்கும் லாபம்",
    salesTracker: "விற்பனை கண்காணிப்பு",
    payModes: "கட்டண முறைகள்",
    receivables: "வரவேண்டியவை",
    monthlyCost: "மாதாந்திர செலவு விவரம்",
    estCostLitre: "ஒரு லிட்டர் செலவு (கணிப்பு)",
    breakeven: "சமநிலை புள்ளி கணக்கீடு",
    scenarioSim: "காட்சி சிமுலேட்டர்",
    cashFlow: "பணப்புழக்கப் பார்வை",

    // Customer Care
    careTitle: "வாடிக்கையாளர் சேவை & மீண்டும் வாங்கல்",
    inbox: "உரையாடல் பெட்டி",
    smartReplies: "ஸ்மார்ட் பதில்கள் & FAQ",
    feedback: "கருத்துகள் & மதிப்பீடுகள்",
    repeatOrders: "மீண்டும் ஆர்டர் & விசுவாசம்",

    // Care Labels
    unifiedInbox: "ஒருங்கிணைந்த இன்பாக்ஸ்",
    quickAdd: "உரையாடலைச் சேர்க்கவும்",
    priorityAlerts: "முக்கிய எச்சரிக்கைகள்",
    faqLibrary: "கேள்வி பதில் வங்கி",
    autoReply: "தானியங்கி பதில் பரிந்துரை",
    feedbackLog: "கருத்து பதிவு",
    satisfaction: "திருப்தி கண்ணோட்டம்",
    repeatTracker: "தொடர் ஆர்டர் கண்காணிப்பு",
    loyalty: "விசுவாசத் திட்டங்கள்",

    // Logistics
    logTitle: "செயல்முறை தளவாட & டெலிவரி திட்டமிடல்",
    strategyOverview: "டெலிவரி உத்தி கண்ணோட்டம்",
    cityPlans: "நகரம் வாரியான திட்டங்கள்",
    costCalc: "செலவு கணிப்பான்",
    routeBatch: "வழித்தட & தொகுதி திட்டமிடல்",

    // Logistics Labels
    keyCities: "முக்கிய நகரங்கள்",
    strategySummary: "உத்தி சுருக்கம்",
    deliveryProfiles: "டெலிவரி விவரங்கள்",
    deliveryPromise: "டெலிவரி உத்தரவாதம்",
    perOrderCalc: "ஒரு ஆர்டர் செலவு கணிப்பு",
    batchPlan: "வரவிருக்கும் தொகுப்புகள்",
    localRoute: "உள்ளூர் வழித்தட மேம்பாடு",

    // Compliance
    compTitle: "சட்ட இணக்கம், உரிமங்கள் & பதிவுகள் (தமிழ்நாடு)",
    compSubtitle: "சிறு உற்பத்தியாளர்களுக்கான வழிகாட்டுதல் - இறுதி முடிவுக்கு நிபுணரை அணுகவும்.",
    overview: "எளிய கண்ணோட்டம்",
    keyRegs: "முக்கிய பதிவுகள்",
    checklists: "நடைமுறை சரிபார்ப்பு பட்டியல்கள்",
    docTracker: "ஆவணம் & புதுப்பித்தல் நினைவூட்டல்கள்",
    
    // Compliance Labels
    whereStand: "உங்கள் நிலை",
    whyMatter: "ஏன் இணக்கம் முக்கியம்?",
    fssai: "FSSAI (உணவு பாதுகாப்பு)",
    gst: "GST (வரி)",
    shops: "கடை உரிமம் / தொழில் உரிமம்",
    labeling: "பேக்கேஜிங் விதிமுறைகள்",
    msme: "MSME / உத்யம் பதிவு",
    askConsultant: "ஆலோசகரிடம் கேட்க வேண்டியவை",
    fssaiPrep: "FSSAI தயார் பட்டியல்",
    labelCheck: "லேபிள் சரிபார்ப்பு",
    bigBuyers: "பெரிய வாங்குபவர்கள் கேட்பவை",

    // Tools
    distCalc: "தூரக் கணிப்பான்",
    priceEngine: "விலை பரிந்துரை இயந்திரம்",
    listExport: "தொடர்பு பட்டியல் ஏற்றுமதி",
    calculate: "கணக்கிடு",
    download: "லீட்ஸ் பதிவிறக்கம் (Excel)",

    // Demo
    startDemo: "டெமோ தொடங்கு (நெய் உற்பத்தியாளர்)",
    demoMode: "டெமோ பயன்முறை",
    demoGuideTitle: "டெமோ வழிகாட்டி – நெய் உற்பத்தியாளர் பயணம்",
    exitDemo: "டெமோவிலிருந்து வெளியேறு",
    nextStep: "அடுத்த படி",
    demoStep1: "வணிக அமைப்பு",
    demoStep1Desc: "திருச்சியில் உள்ள நெய் உற்பத்தியாளரை (20 மாடுகள், 15லி/நாள்) சிஸ்டம் எப்படி புரிந்து கொள்கிறது என்பதைப் பாருங்கள்.",
    demoStep2: "வாடிக்கையாளர்கள் எங்கே",
    demoStep2Desc: "சென்னை/கோவையில் சிறந்த பிரீமியம் வாடிக்கையாளர்களை அடையாளம் காணுதல்.",
    demoStep3: "அவர்களை எப்படி அடைவது",
    demoStep3Desc: "WhatsApp + Instagram பிரச்சாரங்கள் மற்றும் கடை அணுகுமுறையை தானாக வடிவமைத்தல்.",
    demoStep4: "நாம் வழங்க முடியுமா?",
    demoStep4Desc: "உற்பத்தி, இருப்பு மற்றும் இந்த புதிய தேவையை பூர்த்தி செய்ய முடியுமா என சரிபார்த்தல்.",
    demoStep5: "நிதி சாத்தியம்",
    demoStep5Desc: "இந்த நெய் வணிகத்திற்கான வருமானம், செலவுகள் மற்றும் லாப கணிப்புகளைப் பாருங்கள்.",
    demoStep6: "டெலிவரி செய்வது எப்படி?",
    demoStep6Desc: "கூரியர் செலவுகளை கணித்து, திருச்சியிலிருந்து நகரங்களுக்கு அனுப்புவதை திட்டமிடுங்கள்.",
    demoStep7: "வாடிக்கையாளர் சேவை",
    demoStep7Desc: "கேள்விகள், கருத்துக்கள் மற்றும் மீண்டும் வரும் ஆர்டர்களை கையாளுதல்.",
    goToModule: "தொகுதியைத் திறக்கவும்",
    goToSummary: "சுருக்கத்திற்குச் செல்"
  }
};

export const DEMO_DATA = {
  productName: "A2 Cow Ghee (நெய்)",
  category: "Food/Dairy",
  productionCapacity: "15 Litres",
  sellingPrice: 600,
  costPrice: 450,
  experienceLevel: "Have been selling locally",
  revenue: "₹10,000 - ₹50,000",
  salesChannels: ["Local shops"],
  customerCount: "11-50",
  budget: 150000,
  teamSize: "Just me",
  hasSmartphone: true,
  shippingCapability: "Within Tamil Nadu",
  primaryStruggle: "Finding customers who'll pay good price",
  threeMonthGoal: "Double my current sales",
  location: "Tiruchirappalli",
  travelWillingness: "Within 50km"
};
